<?php

$registro['num1'] ='Un medio ambiente limpio es fuente de satisfacción';
$registro['num2'] ='Cuidar el medio ambiente es cuidarnos a nosotros mismos, uno no está separado del otro';
$registro['num3'] ='Ahorrar recursos con los que tengas contacto diario';
$registro['num4'] ='Reciclaje de papel, Reciclaje de vidrio';
$registro['num5'] ='Reducir los envases o productos de usar y tirar';
$registro['num6'] ='Compra solo lo que necesitas';

$registroJson = json_encode($registro);
echo $registroJson
?>